# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_code', models.CharField(max_length=10)),
                ('character', models.TextField()),
                ('length', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_id', models.IntegerField(default=0)),
                ('family_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_code', models.CharField(max_length=10)),
                ('family_id', models.IntegerField(default=0)),
                ('language_name', models.CharField(max_length=200)),
                ('family_order', models.IntegerField(default=0)),
                ('speakers', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_code', models.CharField(max_length=10)),
                ('sentence', models.TextField()),
                ('length', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_code', models.CharField(max_length=10)),
                ('word', models.TextField()),
                ('length', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
