# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 21:47
from __future__ import unicode_literals

from django.db import migrations

def load_families(apps, schema_editor):
    # We can't import the Family model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Family = apps.get_model('lid', 'Family')
    Family.objects.all().delete()

    Family(family_id=1, family_name="Arawak").save()
    Family(family_id=2, family_name="Aru").save()
    Family(family_id=3, family_name="Bora").save()
    Family(family_id=4, family_name="Cahuapana").save()
    Family(family_id=5, family_name="Huitoto").save()
    Family(family_id=6, family_name="Jíbaro").save()
    Family(family_id=7, family_name="Kandozi").save()
    Family(family_id=8, family_name="Pano").save()
    Family(family_id=9, family_name="Peba-yagua").save()
    Family(family_id=10, family_name="Quechua").save()
    Family(family_id=11, family_name="Shimaco").save()
    Family(family_id=12, family_name="Tacana").save()
    Family(family_id=13, family_name="Tikuna").save()
    Family(family_id=14, family_name="Tucano").save()
    Family(family_id=15, family_name="Záparo").save()

def load_languages(apps, schema_editor):
    Language = apps.get_model('lid', 'Language')
    Language.objects.all().delete()

    Language(iso_code="cni", family_id=1, language_name="Asháninka", family_order=1, speakers=88703).save()
    Language(iso_code="cjo", family_id=1, language_name="Ashéninka del Pajonal", family_order=2, speakers=10000).save()
    Language(iso_code="cpu", family_id=1, language_name="Ashéninka del Pichis", family_order=3, speakers=8774).save()
    Language(iso_code="cot", family_id=1, language_name="Kakinte", family_order=4, speakers=439).save()
    Language(iso_code="mcb", family_id=1, language_name="Matsigenka", family_order=5, speakers=11275).save()
    Language(iso_code="not", family_id=1, language_name="Nomatsigenga", family_order=6, speakers=8016).save()
    Language(iso_code="ame", family_id=1, language_name="Yanesha", family_order=7, speakers=7523).save()
    Language(iso_code="pib", family_id=1, language_name="Yine", family_order=8, speakers=3261).save()

    Language(iso_code="aym", family_id=2, language_name="Aymara", family_order=1, speakers=443248).save()
    Language(iso_code="boa", family_id=3, language_name="Bora", family_order=1, speakers=748).save()
    Language(iso_code="cbt", family_id=4, language_name="Shawi", family_order=1, speakers=21650).save()
    Language(iso_code="huu", family_id=5, language_name="Murui", family_order=1, speakers=1864).save()

    Language(iso_code="acu", family_id=6, language_name="Achuar", family_order=1, speakers=11087).save()
    Language(iso_code="agr", family_id=6, language_name="Awajún", family_order=2, speakers=55366).save()
    Language(iso_code="hub", family_id=6, language_name="Wampis", family_order=3, speakers=10163).save()

    Language(iso_code="cbu", family_id=7, language_name="Kandozi", family_order=1, speakers=3255).save()

    Language(iso_code="amc", family_id=8, language_name="Amahuaca", family_order=1, speakers=301).save()
    Language(iso_code="kaq", family_id=8, language_name="Capanahua", family_order=2, speakers=348).save()
    Language(iso_code="cbs", family_id=8, language_name="Cashinahua", family_order=3, speakers=2419).save()
    Language(iso_code="cbr", family_id=8, language_name="Kakataibo", family_order=4, speakers=1879).save()
    Language(iso_code="mcf", family_id=8, language_name="Matsés", family_order=5, speakers=1724).save()
    Language(iso_code="mcd", family_id=8, language_name="Sharanahua", family_order=6, speakers=486).save()
    Language(iso_code="shp", family_id=8, language_name="Shipibo", family_order=7, speakers=22517).save()
    Language(iso_code="yaa", family_id=8, language_name="Yaminahua", family_order=8, speakers=600).save()

    Language(iso_code="yad", family_id=9, language_name="Yagua", family_order=1, speakers=5679).save()

    Language(iso_code="qva", family_id=10, language_name="Quechua de Ambo-Pasco", family_order=1, speakers=90000).save()
    Language(iso_code="quy", family_id=10, language_name="Quechua de Ayacucho", family_order=2, speakers=850050).save()
    Language(iso_code="qvc", family_id=10, language_name="Quechua de Cajamarca", family_order=3, speakers=30000).save()
    Language(iso_code="qub", family_id=10, language_name="Quechua de Huallaga", family_order=4, speakers=40000).save()
    Language(iso_code="qvh", family_id=10, language_name="Quechua de Huamalíes", family_order=5, speakers=72500).save()
    Language(iso_code="quf", family_id=10, language_name="Quechua de Lambayeque", family_order=6, speakers=21496).save()
    Language(iso_code="qvm", family_id=10, language_name="Quechua de Margos", family_order=7, speakers=114000).save()
    Language(iso_code="qxh", family_id=10, language_name="Quechua de Panao", family_order=8, speakers=50000).save()
    Language(iso_code="qvs", family_id=10, language_name="Quechua de San Martin", family_order=9, speakers=44000).save()
    Language(iso_code="qux", family_id=10, language_name="Quechua de Yauyos", family_order=10, speakers=6500).save()
    Language(iso_code="qwh", family_id=10, language_name="Quechua del Callejón de Huaylas", family_order=11, speakers=300000).save()
    Language(iso_code="quz", family_id=10, language_name="Quechua del Cusco", family_order=12, speakers=1115000).save()
    Language(iso_code="qve", family_id=10, language_name="Quechua del Este de Apurimac", family_order=13, speakers=218352).save()
    Language(iso_code="qxn", family_id=10, language_name="Quechua del Norte de Conchucos", family_order=14, speakers=250000).save()
    Language(iso_code="qvn", family_id=10, language_name="Quechua del Norte de Junín", family_order=15, speakers=60000).save()
    Language(iso_code="qvz", family_id=10, language_name="Quechua del Norte de Pastaza", family_order=16, speakers=2100).save()
    Language(iso_code="qxo", family_id=10, language_name="Quechua del Sur de Conchucos", family_order=17, speakers=250000).save()
    Language(iso_code="qup", family_id=10, language_name="Quechua del Sur de Pastaza", family_order=18, speakers=2200).save()
    Language(iso_code="qvw", family_id=10, language_name="Quechua Huaylla Wanca", family_order=19, speakers=298560).save()

    Language(iso_code="ura", family_id=11, language_name="Urarina", family_order=1, speakers=4854).save()
    Language(iso_code="ese", family_id=12, language_name="Ese eja", family_order=1, speakers=588).save()
    Language(iso_code="tca", family_id=13, language_name="Tikuna", family_order=1, speakers=6982).save()
    Language(iso_code="sey", family_id=14, language_name="Secoya", family_order=1, speakers=921).save()
    Language(iso_code="arl", family_id=15, language_name="Arabela", family_order=1, speakers=403).save()


class Migration(migrations.Migration):

    dependencies = [
        ('lid', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_families),
        migrations.RunPython(load_languages),
    ]
