# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 19:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lid', '0002_auto_20170918_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.IntegerField(default=0)),
                ('sentence', models.IntegerField(default=0)),
                ('characters', models.IntegerField(default=0)),
                ('tokens', models.IntegerField(default=0)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lid.Language')),
            ],
        ),
        migrations.CreateModel(
            name='Repository_Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(max_length=200)),
                ('source', models.CharField(max_length=200)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lid.Language')),
            ],
        ),
    ]
