# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 21:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lid', '0003_repository_detail_repository_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inverted_Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Inverted_Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('position', models.IntegerField(default=0)),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lid.Inverted_Sentence')),
            ],
        ),
        migrations.RenameField(
            model_name='repository_detail',
            old_name='sentence',
            new_name='sentences',
        ),
        migrations.AlterField(
            model_name='character',
            name='character',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='repository_source',
            name='source',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='inverted_sentence',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lid.Repository_Source'),
        ),
    ]
