# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lid', '0004_auto_20170919_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository_detail',
            name='tokens',
        ),
        migrations.AddField(
            model_name='repository_detail',
            name='files',
            field=models.IntegerField(default=0),
        ),
    ]
